spring.application.name=catalog-service
server.port=8092

spring.datasource.url=jdbc:postgresql://localhost:5438/catalog_db
spring.datasource.username=flashbuy
spring.datasource.password=flashbuy123

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.export.prometheus.enabled=true
management.endpoint.prometheus.enabled=true