server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5435/inventory_db}
    username: ${DB_USER:flashbuy}
    password: ${DB_PASS:flashbuy123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_INVENTORY_HOST:localhost}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info