name: FlashBuy CI/CD

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: flashbuy-cluster
  GKE_REGION: us-central1
  IMAGE_PREFIX: gcr.io/${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configurar Docker
        run: gcloud auth configure-docker

      - name: Build gateway
        run: docker build -t $IMAGE_PREFIX/gateway:$GITHUB_SHA ./gateway